### ISSUE TITLE
Travis-ci tests not working

### ISSUE THREAD

**Issue by izxle** [vergecurrency/verge-python3#4]
I sent some pull requests and saw that the travis-ci tests all failed, including a pull request with no changes. It seems to be running on python2.7

Traceback (most recent call last):
  File "tests/test.py", line 78, in <module>
    connections = get_connections()
  File "tests/test.py", line 73, in get_connections
    return get_environment_connections()
  File "tests/test.py", line 57, in get_environment_connections
    host = os.environ['HOST']
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)
KeyError: 'HOST'

**Comment by P1R** [comment]
This version is supposed to be for python3 but the Travis-CI uses 2.7, please fix.

**Comment by justinvforvendetta** [comment]
@P1R @izxle updated the travis, and fixed an indent, but im out of town so i wont have alot of time to fix this until friday or saturday, but feel free to check it and make any pull requests you see fit
